schedule:
  - cron: "* * * *"

monitor:
  dir: 
    - "~/.config/subnya/test"
  settings:
    timeout : 30
    threads : 10
    maxenumerationtime: 10
    outdir : "~/.config/subnya/output"
    logdir: "~/.config/subnya/log/"
  
  
redis:
  addr: "172.17.0.1:6379"
  password: "" 
  db:   0 

sqlite:
  db_1: "~/.config/subnya/db/monitor.db"
