schedule:
  - cron: "* * * *"

monitor:
  dir: 
    - "./test"
  settings:
    - timeout : 30
    - threads : 10
    - maxenumerationtime: 10
    - outfile : "./output"
  
  
redis:
  addr: "172.17.0.1:6379"
  password: "" 
  db:   0 

sqlite:
  db_1: "./db/monitor.db"
  